---
# tasks file for ansible-docker-try
- name: Build Docker image from Dockerfile
  docker_image:
    name: ansible_slave
    path: "{{ role_path }}/files/ansible_slave"
    state: build

- name: Create a network
  docker_network:
    name: net1

- name: Create a mongo container
  docker_container:
    name: test_mongodb
    image: mongo
    volumes:
      - /var/opt/mongo/db/:/data/db
    networks:
      - name: net1 


- name: Creates a blank centOs container
  docker_container:
    name: centos_box_1
    image: ansible_slave 
    hostname: serveur1
    networks: 
      - name: net1
        aliases: 
          - serveur1

- name: Creates a blank centOs container
  docker_container:
    name: centos_box_2
    image: ansible_slave
    hostname: serveur2
    networks:
      - name: net1
        aliases: 
          - serveur2


