---

- debug:
    msg: "{{ container }}"
  when: container is defined and debug is defined


- name: "Creating container {{ container.name }}"
  docker_container:
    name: "{{ container.name }}"
    state: "{{ desired_state | default(omit) }}"
    image: "{{ container.image }}"
    hostname: "{{ container.hostname | default(omit) }}"
    volumes: "{{ container.volumes | default(omit) }}"
    networks: "{{ container.networks | default(omit) }}"
    interactive: "{{ container.interactive | default(omit) }}"
    tty: "{{ container.tty | default(omit) }}"
    ports: "{{ container.ports | default(omit) }}"
    restart_policy: "{{ container.restart_policy | default(omit) }}"
  register: creation_result
  when: container is defined


- debug:
    msg: " the image container is not defined ! please define it"
  when: >
      container is not defined
      and debug is defined


- debug:
    msg: "{{ creation_result }}"
  when: >
      creation_result is defined
      and debug is defined
